### ISSUE TITLE
您好：请求帮助，请求您有空时帮帮我

### ISSUE THREAD

**Issue by MINGERTAI** [jadehh/TVSpider#147]
## 您好：请求帮助，请求您有空时帮帮我
我写了个py脚本一直没有成功，模拟打开饭太硬（全能接口解密）https://www.xn--sss604efuw.com/jm/  模拟在输入框输入http://tvbox.王二小放牛娃.top，然后模拟点击解密，结果一直出错！下面是我的py代码，到底是那里出了问题？
```py
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import time

# 配置 Chrome 选项
chrome_options = Options()
chrome_options.add_argument('headless')  # 无头模式
chrome_options.add_argument('no-sandbox')
chrome_options.add_argument('disable-dev-shm-usage')
chrome_options.add_argument('disable-gpu')
chrome_options.add_argument('window-size=1920x1080')  # 设置窗口大小以防止某些元素不可见

# 启动 Chrome 浏览器
driver = webdriver.Chrome(options=chrome_options)
try:
    # 打开解密网站
    driver.get("http://www.xn--sss604efuw.com/jm/")

    # 找到输入框，输入目标 URL
    input_box = driver.find_element(By.ID, "url")
    input_box.send_keys("http://tvbox.王二小放牛娃.top")

    # 点击解密按钮
    decrypt_button = driver.find_element(By.XPATH, "//button[contains(text(),'解密')]")
    decrypt_button.click()

    # 等待解密完成
    time.sleep(5)  # 根据实际情况调整等待时间

    # 点击复制按钮
    copy_button = driver.find_element(By.XPATH, "//button[contains(text(),'复制')]")
    copy_button.click()

    # 获取解密后的内容
    decrypted_content = driver.find_element(By.ID, "result").get_attribute("value")

    # 删除原有的 ./out/new.txt 文件（如果存在）
    output_path = "./out/new.txt"
    if os.path.exists(output_path):
        os.remove(output_path)
        print('已删除原有的 ./out/new.txt 文件。')

    # 将内容保存到文件
    with open(output_path, "w", encoding="utf-8") as file:
        file.write(decrypted_content)

    print(f'解密内容已保存到 {output_path}')

finally:
    # 关闭浏览器
    driver.quit()
```
下面是github Actions出错的代码
```
Traceback (most recent call last):
  File "/home/runner/work/url/url/./TVUrl-check/main.py", line 21, in <module>
    input_box = driver.find_element(By.ID, "url")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.[12](https://github.com/ne7359/url/actions/runs/9974448584/job/27561939363#step:5:13).4/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="url"]"}
  (Session info: chrome-headless-shell=126.0.6478.126); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55977250ac7a <unknown>
#1 0x5597721ede2c <unknown>
#2 0x55977223a661 <unknown>
#3 0x55977223a751 <unknown>
#4 0x55977227ef64 <unknown>
#5 0x55977225d5ed <unknown>
#6 0x55977227c303 <unknown>
#7 0x55977225d363 <unknown>
#8 0x55977222d247 <unknown>
#9 0x55977222db9e <unknown>
#10 0x5597724d124b <unknown>
#11 0x5597724d52f1 <unknown>
#12 0x5597724bcafe <unknown>
#[13](https://github.com/ne7359/url/actions/runs/9974448584/job/27561939363#step:5:14) 0x5597724d5e52 <unknown>
#14 0x5597724a179f <unknown>
#15 0x5597724fa638 <unknown>
#16 0x5597724fa810 <unknown>
#17 0x559772509dac <unknown>
#18 0x7fe5a0094ac3 <unknown>
Error: Process completed with exit code 1.
```
下面是饭太硬网页代码

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>加密接口解析提取</title>
    <!-- 引入Bootstrap样式库 -->
    <link rel="stylesheet" href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.0.0/css/bootstrap.min.css">
    <style>
        body {
            margin-top: 40px;
        }

        .container {
            max-width: 800px;
            margin: 0 auto;
            padding: 0 15px;
        }

        .input-group {
            margin-bottom: 20px;
        }

        .loading {
            display: none;
            margin-top: 20px;
        }

        @media (max-width: 768px) {
            .container {
                max-width: 100%;
            }
        }
    </style>
</head>

<body>
    <div class="container">
        <h1 class="text-center mb-5">全能接口解密</h1>
        <div class="input-group mb-3">
            <input type="text" class="form-control" id="url" value="" placeholder="输入接口地址，没地址？饭太硬主页有">
            <button class="btn btn-secondary" type="button" onclick="if (!window.__cfRLUnblockHandlers) return false; crawl()" data-cf-modified-a230b8237e579d3c1297faf6-="">解密</button>
        </div>

        <div class="text-center loading" id="loading">
            <div class="spinner-border" role="status">
                野<span class="visually-hidden">Loading...</span>
            </div>
        </div>

        <textarea class="form-control" id="result" cols="80" rows="20" readonly></textarea>
        <div class="text-center mt-3">
            <a href="https://饭太硬.com" target="_blank" class="btn btn-primary">主页</a>
            <button class="btn btn-warning" onclick="if (!window.__cfRLUnblockHandlers) return false; copyText()" data-cf-modified-a230b8237e579d3c1297faf6-="">复制</button>
            <!--<button class="btn btn-success" onclick="downloadJar()">下载Jar</button>-->
            <a href="https://mp.weixin.qq.com/s/nP3-qdiuHuGCh3rXE8qLDw" target="_blank" class="btn btn-danger">饭太硬公众号</a>

        </div>
    </div>
    <!-- 引入Bootstrap JS库 -->
    <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/5.0.0/js/bootstrap.min.js" type="a230b8237e579d3c1297faf6-text/javascript"></script>
    <script type="a230b8237e579d3c1297faf6-text/javascript">
        function crawl() {
            var xhr = new XMLHttpRequest();
            var url = document.getElementById('url').value;
            var resultBox = document.getElementById('result');
            xhr.open("GET", "./jiemi.php?url=" + encodeURIComponent(url), true);
            xhr.onreadystatechange = function() {
                if (xhr.readyState == 4 && xhr.status == 200) {
                    resultBox.value = xhr.responseText;
                    document.getElementById('loading').style.display = 'none';
                }
            };
            resultBox.value = '';
            document.getElementById('loading').style.display = 'block';
            xhr.send();
        }

        function downloadJar() {
            var resultBox = document.getElementById('result');
            var url = resultBox.value.match(/"spider":"(.*?)"/)[1];
            if (url.includes(';md5;')) {
                url = url.split(';md5;')[0];
            }
            fetch(url, {
                    headers: {
                        'User-Agent': 'okhttp'
                    }
                })
                .then(function(response) {
                    return response.blob();
                })
                .then(function(blob) {
                    var downloadUrl = URL.createObjectURL(blob);
                    var a = document.createElement('a');
                    a.href = downloadUrl;
                    a.download = 'file.jar';
                    a.click();
                    URL.revokeObjectURL(downloadUrl);
                    document.getElementById('loading').style.display = 'none';
                });
            document.getElementById('loading').style.display = 'block';
        }

        function copyText() {
            var copyText = document.getElementById("result");
            copyText.select();
            copyText.setSelectionRange(0, 99999);
            document.execCommand("copy");
            alert("偷取成功！");
        }
    </script>
    <script src="/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js" data-cf-settings="a230b8237e579d3c1297faf6-|49" defer></script>
    <script>
        (function() {
            function c() {
                var b = a.contentDocument || a.contentWindow.document;
                if (b) {
                    var d = b.createElement('script');
                    d.innerHTML = "window.__CF$cv$params={r:'8a0461333cbe5dee',t:'MTcyMDQ4Njg1My4wMDAwMDA='};var a=document.createElement('script');a.nonce='';a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);";
                    b.getElementsByTagName('head')[0].appendChild(d)
                }
            }
            if (document.body) {
                var a = document.createElement('iframe');
                a.height = 1;
                a.width = 1;
                a.style.position = 'absolute';
                a.style.top = 0;
                a.style.left = 0;
                a.style.border = 'none';
                a.style.visibility = 'hidden';
                document.body.appendChild(a);
                if ('loading' !== document.readyState) c();
                else if (window.addEventListener) document.addEventListener('DOMContentLoaded', c);
                else {
                    var e = document.onreadystatechange || function() {};
                    document.onreadystatechange = function(b) {
                        e(b);
                        'loading' !== document.readyState && (document.onreadystatechange = e, c())
                    }
                }
            }
        })();
    </script>
</body>
</html>
```

**Comment by ne7359** [comment]
# 已解决，谢谢您一直以来的帮助，谢谢了
